In [1]:
DATA = './dataset/matches.csv'

In [2]:
import pandas as pd

In [3]:
data=pd.read_csv(DATA)

In [4]:
data.columns

Index(['id', 'Season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='object')

In [5]:
data.info

<bound method DataFrame.info of         id    Season           city        date                        team1  \
0        1  IPL-2017      Hyderabad  05-04-2017          Sunrisers Hyderabad
1        2  IPL-2017           Pune  06-04-2017               Mumbai Indians
2        3  IPL-2017         Rajkot  07-04-2017                Gujarat Lions
3        4  IPL-2017         Indore  08-04-2017       Rising Pune Supergiant
4        5  IPL-2017      Bangalore  08-04-2017  Royal Challengers Bangalore
..     ...       ...            ...         ...                          ...
751  11347  IPL-2019         Mumbai  05-05-2019        Kolkata Knight Riders
752  11412  IPL-2019        Chennai  07-05-2019          Chennai Super Kings
753  11413  IPL-2019  Visakhapatnam  08-05-2019          Sunrisers Hyderabad
754  11414  IPL-2019  Visakhapatnam  10-05-2019               Delhi Capitals
755  11415  IPL-2019      Hyderabad  12-05-2019               Mumbai Indians

                           team2                  toss_winner toss_decision  \
0    Royal Challengers Bangalore  Royal Challengers Bangalore         field
1         Rising Pune Supergiant       Rising Pune Supergiant         field
2          Kolkata Knight Riders        Kolkata Knight Riders         field
3                Kings XI Punjab              Kings XI Punjab         field
4               Delhi Daredevils  Royal Challengers Bangalore           bat
..                           ...                          ...           ...
751               Mumbai Indians               Mumbai Indians         field
752               Mumbai Indians          Chennai Super Kings           bat
753               Delhi Capitals               Delhi Capitals         field
754          Chennai Super Kings          Chennai Super Kings         field
755          Chennai Super Kings               Mumbai Indians           bat

     result  dl_applied                       winner  win_by_runs  \
0    normal           0          Sunrisers Hyderabad           35
1    normal           0       Rising Pune Supergiant            0
2    normal           0        Kolkata Knight Riders            0
3    normal           0              Kings XI Punjab            0
4    normal           0  Royal Challengers Bangalore           15
..      ...         ...                          ...          ...
751  normal           0               Mumbai Indians            0
752  normal           0               Mumbai Indians            0
753  normal           0               Delhi Capitals            0
754  normal           0          Chennai Super Kings            0
755  normal           0               Mumbai Indians            1

     win_by_wickets player_of_match  \
0                 0    Yuvraj Singh
1                 7       SPD Smith
2                10         CA Lynn
3                 6      GJ Maxwell
4                 0       KM Jadhav
..              ...             ...
751               9       HH Pandya
752               6        AS Yadav
753               2         RR Pant
754               6    F du Plessis
755               0       JJ Bumrah

                                         venue         umpire1  \
0    Rajiv Gandhi International Stadium, Uppal     AY Dandekar
1      Maharashtra Cricket Association Stadium  A Nand Kishore
2       Saurashtra Cricket Association Stadium     Nitin Menon
3                       Holkar Cricket Stadium    AK Chaudhary
4                        M Chinnaswamy Stadium             NaN
..                                         ...             ...
751                           Wankhede Stadium   Nanda Kishore
752                  M. A. Chidambaram Stadium     Nigel Llong
753                           ACA-VDCA Stadium             NaN
754                           ACA-VDCA Stadium   Sundaram Ravi
755         Rajiv Gandhi Intl. Cricket Stadium     Nitin Menon

            umpire2                  umpire3
0          NJ Llong                      NaN
1            S Ravi                      NaN
2         CK Nandan                      NaN
3     C Shamshuddin                      NaN
4               NaN                      NaN
..              ...                      ...
751        O Nandan                   S Ravi
752     Nitin Menon                Ian Gould
753             NaN                      NaN
754  Bruce Oxenford  Chettithody Shamshuddin
755       Ian Gould              Nigel Llong

[756 rows x 18 columns]>

# Q1

In [6]:
# Q1
print('Total Matches: ', data.shape[0])
print('\nColumns')
for col in data.columns:
    print(col)
print('\n5 rows of data')
print(data.head(5))
print('\ndescribe data')
data.describe()

Total Matches:  756

Columns
id
Season
city
date
team1
team2
toss_winner
toss_decision
result
dl_applied
winner
win_by_runs
win_by_wickets
player_of_match
venue
umpire1
umpire2
umpire3

5 rows of data
   id    Season       city        date                        team1  \
0   1  IPL-2017  Hyderabad  05-04-2017          Sunrisers Hyderabad
1   2  IPL-2017       Pune  06-04-2017               Mumbai Indians
2   3  IPL-2017     Rajkot  07-04-2017                Gujarat Lions
3   4  IPL-2017     Indore  08-04-2017       Rising Pune Supergiant
4   5  IPL-2017  Bangalore  08-04-2017  Royal Challengers Bangalore

                         team2                  toss_winner toss_decision  \
0  Royal Challengers Bangalore  Royal Challengers Bangalore         field
1       Rising Pune Supergiant       Rising Pune Supergiant         field
2        Kolkata Knight Riders        Kolkata Knight Riders         field
3              Kings XI Punjab              Kings XI Punjab         field
4             Delhi Daredevils  Royal Challengers Bangalore           bat

   result  dl_applied                       winner  win_by_runs  \
0  normal           0          Sunrisers Hyderabad           35
1  normal           0       Rising Pune Supergiant            0
2  normal           0        Kolkata Knight Riders            0
3  normal           0              Kings XI Punjab            0
4  normal           0  Royal Challengers Bangalore           15

   win_by_wickets player_of_match                                      venue  \
0               0    Yuvraj Singh  Rajiv Gandhi International Stadium, Uppal
1               7       SPD Smith    Maharashtra Cricket Association Stadium
2              10         CA Lynn     Saurashtra Cricket Association Stadium
3               6      GJ Maxwell                     Holkar Cricket Stadium
4               0       KM Jadhav                      M Chinnaswamy Stadium

          umpire1        umpire2 umpire3
0     AY Dandekar       NJ Llong     NaN
1  A Nand Kishore         S Ravi     NaN
2     Nitin Menon      CK Nandan     NaN
3    AK Chaudhary  C Shamshuddin     NaN
4             NaN            NaN     NaN

describe data

                 id  dl_applied  win_by_runs  win_by_wickets
count    756.000000  756.000000   756.000000      756.000000
mean    1792.178571    0.025132    13.283069        3.350529
std     3464.478148    0.156630    23.471144        3.387963
min        1.000000    0.000000     0.000000        0.000000
25%      189.750000    0.000000     0.000000        0.000000
50%      378.500000    0.000000     0.000000        4.000000
75%      567.250000    0.000000    19.000000        6.000000
max    11415.000000    1.000000   146.000000       10.000000

# Q2

In [40]:
da1=data['player_of_match'].where(data['win_by_runs']==int(1))
da2=data['player_of_match'].where(data['win_by_wickets']==int(1))

In [41]:
da1

0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
         ...
751          NaN
752          NaN
753          NaN
754          NaN
755    JJ Bumrah
Name: player_of_match, Length: 756, dtype: object

In [47]:
da1.isna().value_counts()

player_of_match
True     746
False     10
Name: count, dtype: int64

In [49]:
da2

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
751    NaN
752    NaN
753    NaN
754    NaN
755    NaN
Name: player_of_match, Length: 756, dtype: object

In [48]:
da2.isna().value_counts()

player_of_match
True     753
False      3
Name: count, dtype: int64

In [50]:
new_data=pd.merge(da1, da2, on=['player_of_match'], how='outer')

In [52]:
new_data['player_of_match'].where(new_data['player_of_match'].notnull())

0            A Nehra
1         AD Russell
2          CH Morris
3           DJ Bravo
4          JJ Bumrah
             ...
561746           NaN
561747           NaN
561748           NaN
561749           NaN
561750           NaN
Name: player_of_match, Length: 561751, dtype: object

# Q3

In [22]:
data.head()

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [58]:
std=data[data['venue'].str.contains("Wankhede Stadium", case=False, na=False)]
wbr=std[std['win_by_runs']>0].shape[0]
wbw=std[std['win_by_wickets']>0].shape[0]
if wbr>wbw:
    print('Win by batting first')
else:
    print('batting second')

batting second

# Q4

In [ ]:
data.head()

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [8]:
data['winner']

0              Sunrisers Hyderabad
1           Rising Pune Supergiant
2            Kolkata Knight Riders
3                  Kings XI Punjab
4      Royal Challengers Bangalore
                  ...
751                 Mumbai Indians
752                 Mumbai Indians
753                 Delhi Capitals
754            Chennai Super Kings
755                 Mumbai Indians
Name: winner, Length: 756, dtype: object

In [10]:
data['winner'].where(data['win_by_runs']>int(50)).value_counts()

winner
Chennai Super Kings            13
Mumbai Indians                 10
Royal Challengers Bangalore     7
Rajasthan Royals                6
Kings XI Punjab                 4
Delhi Daredevils                4
Kolkata Knight Riders           3
Deccan Chargers                 3
Sunrisers Hyderabad             2
Rising Pune Supergiant          1
Name: count, dtype: int64

# Q5

In [15]:
data.head()

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [53]:
new_data=(data['toss_winner']==data['winner'])&(data['win_by_runs']>0)

In [55]:
res=new_data.sum()
print(res)

135

# Q6

In [16]:
data.head()

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [17]:
data.dtypes

id                  int64
Season             object
city               object
date               object
team1              object
team2              object
toss_winner        object
toss_decision      object
result             object
dl_applied          int64
winner             object
win_by_runs         int64
win_by_wickets      int64
player_of_match    object
venue              object
umpire1            object
umpire2            object
umpire3            object
dtype: object

In [31]:
d1=data[['umpire1', 'umpire2']].where(data['team1']=='Kolkata Knight Riders')
d2=data[['umpire1', 'umpire2']].where(data['team2']=='Kolkata Knight Riders')
# d1.notnull().value_counts()+d2.notnull().value_counts()
d1.where(d1.notnull()).value_counts()+d2.where(d2.notnull()).value_counts()

umpire1          umpire2
A Deshmukh       NJ Llong          NaN
A Nand Kishore   BNJ Oxenford      NaN
                 S Ravi            NaN
A Nanda Kishore  Anil Chaudhary    NaN
AK Chaudhary     CK Nandan         3.0
                                  ...
SK Tarapore      SJA Taufel        NaN
SL Shastri       RB Tiffin         NaN
SS Hazare        RB Tiffin         NaN
                 SJA Taufel        3.0
Yeshwant Barde   O Nandan          NaN
Name: count, Length: 130, dtype: float64